version: "3"

services:
  db-postgres-backend:
    image: postgres:alpine
    ports:
      - "5432:5432"
    container_name: "db-postgres-backend"
    restart: always
    volumes:
      - ./bd:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
volumes:
  db: